In [1]:
import numpy as np

In [2]:
#Create a 1D array from a list
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)


1D Array: [1 2 3 4 5]


In [3]:
# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))
print("3x3 Zeros Array:\n", zeros_array)

3x3 Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#Create a 2x2 array of ones
ones_array = np.ones((2, 2))
print("2x2 Ones Array:\n", ones_array)


2x2 Ones Array:
 [[1. 1.]
 [1. 1.]]


In [5]:
#Generate array from 0 to 10 (exclusive)
range_array = np.arange(0, 10)
print("Array from 0 to 10 (exclusive):", range_array)



Array from 0 to 10 (exclusive): [0 1 2 3 4 5 6 7 8 9]


In [6]:
# Create 5 evenly spaced numbers between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print("5 evenly spaced numbers between 0 and 1:", linspace_array)


5 evenly spaced numbers between 0 and 1: [0.   0.25 0.5  0.75 1.  ]


In [7]:
#Create a 4x4 identity matrix
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:\n", identity_matrix)


4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
#Reshape 1D array to 2D
reshaped_array = array_1d.reshape((1, 5))  # or (5, 1)
print("Reshaped to 2D:\n", reshaped_array)


Reshaped to 2D:
 [[1 2 3 4 5]]


In [9]:
#Get the shape and dtype of an array
print("Shape:", array_1d.shape)
print("Dtype:", array_1d.dtype)


Shape: (5,)
Dtype: int64


In [10]:
#Reverse a NumPy array
reversed_array = array_1d[::-1]
print("Reversed Array:", reversed_array)


Reversed Array: [5 4 3 2 1]


In [12]:
#Extract even numbers from an array
even_numbers = array_1d[array_1d % 2 == 0]
print("Even Numbers:",even_numbers)

Even Numbers: [2 4]


In [15]:
#Find the max in each row
arr = np.array([[1, 5, 2], [7, 3, 9]])
row_max = np.max(arr, axis=1)
print("Max in each row:",row_max)


Max in each row: [5 9]


In [16]:
#Compute mean, std, and median
arr = np.array([1,2,3,4,5,6])
mean = np.mean(arr)
std = np.std(arr)
median = np.median(arr)
print("Mean:", mean, "Std:", std, "Median:",median)

Mean: 3.5 Std: 1.707825127659933 Median: 3.5


In [17]:
#Stack two arrays vertically
a = np.array([1, 2])
b = np.array([3, 4])
vstack = np.vstack((a, b))
print("Vertical stack:\n",vstack)

Vertical stack:
 [[1 2]
 [3 4]]


In [19]:
#Stack two arrays horizontally
a = np.array([[1], [2]])
b = np.array([[3], [4]])
hstack = np.hstack((a, b))
print("Horizontal stack:\n",hstack)

Horizontal stack:
 [[1 3]
 [2 4]]


In [20]:
#Find unique values and their counts
arr = np.array([1, 2, 2, 3, 1, 4])
unique, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique)
print("Counts:",counts)

Unique values: [1 2 3 4]
Counts: [2 2 1 1]


In [21]:
#Replace NaN with column means
arr = np.array([[np.nan, 2, 3], [4, np.nan, 6], [7, 8, np.nan]])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print("NaNs replaced:\n",arr)

NaNs replaced:
 [[5.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  4.5]]


In [22]:
#Get index of min and max values
arr = np.array([[10, 20], [5, 30]])
min_index = np.unravel_index(np.argmin(arr), arr.shape)
max_index = np.unravel_index(np.argmax(arr), arr.shape)
print("Min index:", min_index)
print("Max index:",max_index)

Min index: (np.int64(1), np.int64(0))
Max index: (np.int64(1), np.int64(1))


In [23]:
#Create a 3D array of random integers
random_3d = np.random.randint(0, 100, size=(2, 3, 4))
print("3D random array:\n",random_3d)

3D random array:
 [[[63 51 39 26]
  [63 33 63 29]
  [31 82 47 96]]

 [[15 76  5 34]
  [99 24 91  8]
  [ 3 47  8  4]]]


In [24]:
#Use np.where() to replace values
arr = np.array([10, 15, 20, 25])
new_arr = np.where(arr > 20, 100, arr)
print("Replaced values:",new_arr)

Replaced values: [ 10  15  20 100]


In [1]:
#Pandas
#1. Create a Series using a Python list.
import pandas as pd

# Python list
data = [10, 20, 30, 40, 50]

# Create Series
series = pd.Series(data)

# Display the Series
print(series)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [2]:
#2. Create a Series with custom string indices.
import pandas as pd

# Data and custom indices
data = [100, 200, 300]
indices = ['Math', 'Science', 'English']

# Create Series
series = pd.Series(data, index=indices)

# Display the Series
print(series)


Math       100
Science    200
English    300
dtype: int64


In [3]:
#3. Create a Series from a dictionary.
import pandas as pd

# Dictionary
data = {'Math': 90, 'Science': 85, 'English': 88}

# Create Series
series = pd.Series(data)

# Display the Series
print(series)


Math       90
Science    85
English    88
dtype: int64


In [4]:
#4. Access first 3 elements of a Series.
import pandas as pd

series = pd.Series([10, 20, 30, 40, 50])
print(series[:3])


0    10
1    20
2    30
dtype: int64


In [5]:
#5. Filter Series elements greater than 50.
import pandas as pd

# Create Series
series = pd.Series([45, 60, 30, 75, 90])

# Filter elements > 50
filtered_series = series[series > 50]

# Display result
print(filtered_series)


1    60
3    75
4    90
dtype: int64


In [6]:
#6. Add two Series with different indices.
import pandas as pd

# Two Series with different indices
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([5, 15, 25], index=['b', 'c', 'd'])

# Add the Series
result = s1 + s2

# Display result
print(result)


a     NaN
b    25.0
c    45.0
d     NaN
dtype: float64


In [7]:
#7. Multiply a Series by a scalar.
import pandas as pd

# Create Series
series = pd.Series([10, 20, 30, 40])

# Multiply by scalar
result = series * 2

# Display result
print(result)


0    20
1    40
2    60
3    80
dtype: int64


In [8]:
#8. Use .multiply() method to multiply with scalar.
import pandas as pd

# Create Series
series = pd.Series([5, 10, 15, 20])

# Multiply using .multiply()
result = series.multiply(3)

# Display result
print(result)


0    15
1    30
2    45
3    60
dtype: int64


In [9]:
#10. Sort Series by values descending.
import pandas as pd

# Create Series
series = pd.Series([25, 80, 45, 60, 10])

# Sort by values in descending order
sorted_series = series.sort_values(ascending=False)

# Display result
print(sorted_series)


1    80
3    60
2    45
0    25
4    10
dtype: int64


In [10]:
#11. Sort Series by index.
import pandas as pd

# Create Series with unordered indices
series = pd.Series([100, 200, 300], index=['b', 'c', 'a'])

# Sort by index
sorted_series = series.sort_index()

# Display result
print(sorted_series)


a    300
b    100
c    200
dtype: int64


In [11]:
#12. Check for null values.
import pandas as pd

# Create Series with a null value
series = pd.Series([10, None, 30, None, 50])

# Check for null values
null_check = series.isnull()

# Display result
print(null_check)


0    False
1     True
2    False
3     True
4    False
dtype: bool


In [12]:
#import pandas as pd

# Create two Series
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([40, 50, 60])

# Concatenate using concat()
result = pd.concat([s1, s2])

# Display result
print(result)



0    10
1    20
2    30
0    40
1    50
2    60
dtype: int64


In [14]:
#15. Concatenate two Series using append().
import pandas as pd

# Create two Series
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

# Concatenate using append()
result = pd.concat([s1, s2])

# Display result
print(result)


0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


In [15]:
#16. Retrieve first 5 elements using .head()
import pandas as pd

# Create a Series
series = pd.Series([10, 20, 30, 40, 50, 60, 70])

# Get first 5 elements
first_five = series.head()

# Display result
print(first_five)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [16]:
#17. Retrieve last 5 elements using .tail()
import pandas as pd

# Create a Series
series = pd.Series([5, 10, 15, 20, 25, 30, 35, 40])

# Get last 5 elements
last_five = series.tail()

# Display result
print(last_five)


3    20
4    25
5    30
6    35
7    40
dtype: int64


In [17]:
#18. Convert Series to DataFrame.
import pandas as pd

# Create a Series
series = pd.Series([100, 200, 300], index=['A', 'B', 'C'])

# Convert to DataFrame
df = series.to_frame(name='Marks')

# Display result
print(df)


   Marks
A    100
B    200
C    300


In [18]:
#19. Replace NaN with 0.
import pandas as pd
import numpy as np

# Create Series with NaN values
series = pd.Series([10, np.nan, 30, None, 50])

# Replace NaN with 0
clean_series = series.fillna(0)

# Display result
print(clean_series)


0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64


In [19]:
#20. Drop missing values.
import pandas as pd
import numpy as np

# Create a Series with missing values
series = pd.Series([100, None, 200, np.nan, 300])

# Drop missing values
clean_series = series.dropna()

# Display result
print(clean_series)


0    100.0
2    200.0
4    300.0
dtype: float64


In [20]:
#21. Check Series data type.
import pandas as pd

# Create a Series
series = pd.Series([10, 20, 30])

# Check data type
print(series.dtype)


int64
